### ISSUE TITLE
Allow Empty String for -Exchange

### ISSUE THREAD

**Issue by derekmwright** [RamblingCookieMonster/PSRabbitMq#11]
Passing -Exchange an empty string should resort to the "default" exchange in RabbitMQ. 

Taken from: https://www.rabbitmq.com/tutorials/tutorial-three-java.html

> Nameless exchange
> 
> In previous parts of the tutorial we knew nothing about exchanges, but still were able to send messages to queues. That was possible because we were using a default exchange, which we identify by the empty string ("").
> 
> Recall how we published a message before:
> 
> channel.basicPublish("", "hello", null, message.getBytes());
> The first parameter is the the name of the exchange. The empty string denotes the default or nameless exchange: messages are routed to the queue with the name specified by routingKey, if it exists.

**Comment by gaelcolas** [comment]
ohh, I thought I fixed that... maybe I haven't pushed it...
I'll have to check.

**Comment by gaelcolas** [comment]
This one can be closed ;)

**Comment by RamblingCookieMonster** [comment]
Awesome, thanks!
