### ISSUE TITLE
Possibility to reduce parameter definitions

### ISSUE THREAD

**Issue by derekmwright** [RamblingCookieMonster/PSRabbitMq#15]
One thing I've been working on lately is DRY'ing out my PowerShell code, especially when it comes to defining parameters. Coming from Ruby, I can't stand how a PowerShell function isn't able to inherit parameter declarations from another base function. This feeling was unpleasant so I attempted to work around it. I noticed the code here has quite a few repeat parameters. This will allow you to define some common parameters and load them into a function:

https://gist.github.com/derekmwright/91504970eb876ca4ff9c6c5714ada2ef

It's still a little bit of a work in progress, but I figure more eyes is a good thing and maybe it can benefit. Esp w/ the chatter of a possible version bump.

**Comment by gaelcolas** [comment]
Although I agree that the Parameter are very verbose, I think it's a good thing to keep it that way.
The main problems I have with over-using the Dynamic parameters are the following:
- Parameter Sets are much harder to manage especially if you have a mix of Dynamic and non Dynamic
- lest explicit, so the IDE does not alert you of conflicts/errors
- _Centrally_ defining the parameters for several functions makes your code harder to read

When using a single file functions design as this project follows, I found it actually easier to maintain, as when you come back to the project after a while, if you only need to change a function you have to only check one file.

The _hardest_ part with this approach is to be consistent with the name and type of parameters, which is an interesting and relatively easy thing to handle with Pester.

When the signature of a function is partly or completely the same, or as you put it, a function extend another one, then I'd rather resort to [proxy functions](https://blogs.technet.microsoft.com/heyscriptingguy/2011/03/01/proxy-functions-spice-up-your-powershell-core-cmdlets/).

**Comment by derekmwright** [comment]
Ooo thanks for Proxy Functions, I'm still learning PowerShell so I appreciate the guidance there.
