### ISSUE TITLE
Question about a "retrieve loop" to drain a queue with multiple items in it. 

### ISSUE THREAD

**Issue by NealWalters** [RamblingCookieMonster/PSRabbitMq#23]
If I have a queue with 3 items in it, should this drain the queue and display each item? 

```
$maxLoops = 5 
For ($i=0; $i -le $maxLoops; $i++) 
{
    $Incoming = Wait-RabbitMqMessage -Exchange $Exchange -Key $QueueName -QueueName $QueueName -Timeout 20 -vhost base @Params
    Write-Host $Incoming 
}
```

It pauses 20 seconds, then the Write-Host statement displays only the first item in the queue 
From the RabbitMQ web interface, I see the queue empty after running this. 

Thanks,
Neal

**Comment by NealWalters** [comment]
Okay, now I found you have a Start-RabbitMQListener - but I don't understand where it sends the message to variables so I can handle them. 

Neal

**Comment by derekmwright** [comment]
Here's how I use the listener (I encode my messages as json)

```powershell
Start-RabbitMqListener -ComputerName 'rabbitmqhost.example.com' `
                       -Exchange 'powershell' `
                       -Key 'script_execution' `
                       -QueueName 'script_execution' `
                       -AutoDelete $false `
                       -Durable $false `
                       -Credential $creds `
                       -Ssl Tls12 | %{ # Might want to change this to a For-Each as I guess this syntax is bad manners...
    $req = $_ | ConvertFrom-Json
    # Do stuff with $req
    }
}
```
This will run forever and each time an object is retreived the logic in for For-Each loop is executed.

**Comment by NealWalters** [comment]
Thanks that's what I was looking for!  I didn't know you were supposed to pipe it to a for-each loop (and I didn't remember the % sign was a short cut for for-each). 

Two follow-up questions: 
1) What if you want to drain a queue that already has data in it?  Does above only listen for new items queued? 
2) I have two Powershell windows open, and when I store new messages in the queue quickly, the above code seems to miss a few of them.  (I put a Write-Host where you had "#Do stuff").  Actually seems like it's missing every other one. 

Thanks,
Neal
