### ISSUE TITLE
How to reply to a message?

### ISSUE THREAD

**Issue by schneidr** [RamblingCookieMonster/PSRabbitMq#26]
I'm implementing RPC via [direct reply-to](https://www.rabbitmq.com/direct-reply-to.html) messages. The PHP part that sends a request works, I get the request in PowerShell, but I find nothing on how to send back an acknowledgement.

working variant 1:

    while ($true) {
        Try {
            $data = Wait-RabbitMqMessage -Exchange $ExchangeName -Key $QueueName -QueueName $QueueName -Timeout 120 @Params -ErrorAction SilentlyContinue
            $data = $data |ConvertFrom-Json
            $data
        } Catch {
            # do nothing
            $_.Exception
        }
    }

working variant 2:

    Start-RabbitMqListener -ComputerName 'localhost' -Exchange $ExchangeName -QueueName $QueueName -Key $QueueName -Credential $credentials |% { $_ }

Both variants print out the message. But all I get is a string ... how do I send a response?

**Comment by gpduck** [comment]
I think using the -IncludeEnvelope parameter (with either method) will give you an object that includes the headers (including properties.reply_to and properties.reply_to_address) which should give you what you need to craft the response (using Send-RabbitMqMessage).

**Comment by schneidr** [comment]
Thanks, that was the key.

For completeness, when somebody runs into the same problem, this is how I got it working:

    $data = Wait-RabbitMqMessage -Exchange $ExchangeName -QueueName $QueueName -Key $QueueName `
    	-Timeout 120 -IncludeEnvelope @Params -ErrorAction SilentlyContinue
    $return = @{
        result = 'ok'
    }
    # do whatever you want with $data.payload, store your result in $return
    Send-RabbitMqMessage -ReplyTo $data.properties.reply_to -Key $data.properties.reply_to -DeliveryMode 2 `
        -CorrelationID $data.properties.correlation_id -ContentType 'application/json' `
        @Params -InputObject $return
