### ISSUE TITLE
Not being able to specify a port other than the default ones (non-ssl and ssl).

### ISSUE THREAD

**Issue by th0sxph** [RamblingCookieMonster/PSRabbitMq#34]
It is not possible to specify other ports other than the default ones when using the following functions `Register-RabbitMqEvent` and `Send-RabbitMqMessage`. 

Proposed changes on the following pull request:
`Pull request `#33 

Thank you

**Comment by yuvalmarciano** [comment]
We can close this issue, can't we? @th0sxph

**Comment by th0sxph** [comment]
> We can close this issue, can't we? @th0sxph

Closed. Sorry for the late reply.
