### ISSUE TITLE
Complementary Module

### ISSUE THREAD

**Issue by mrhockeymonkey** [RamblingCookieMonster/PSRabbitMq#35]
Hi @RamblingCookieMonster 

I have been using this module with great success on PS 5.1 so thank you for your hard work. I did however run into issues when trying to use on Linux in PS 7.0. I can go into detail on why but to suit my purposes (and as a learning experience) I have created a new module to complement PSRabbitMQ, focusing on Consuming.

It is yet very simple and a work in progress but I thought it might be worth sharing via the PSGallery. So far I have named it `PSRabbitMq.Consumer`  as it is intended to be used _with_ your module. 

Would you be happy for me to publish such a module? As far as i know you haven't copyrighted the name but I felt that I would like to have your approval out of courtesy. 

You can find my module [here](https://github.com/mrhockeymonkey/PSRabbitMq.Consumer). All feedback and questions welcome.

**Comment by RamblingCookieMonster** [comment]
sounds awesome, thanks for the heads up  : D
